#
# This file was automatically generated by the hrlAnalysis Software.
#

def getCellGroups():
	cellGroup = []
	cellGroup.append({"name":"Outputs","startIdx":0,"endIdx":29})
	cellGroup.append({"name":"Inputs","startIdx":60,"endIdx":89})
	cellGroup.append({"name":"Control1","startIdx":57,"endIdx":59})
	cellGroup.append({"name":"Control2","startIdx":54,"endIdx":56})
	cellGroup.append({"name":"Control3","startIdx":51,"endIdx":53})
	cellGroup.append({"name":"Control4","startIdx":48,"endIdx":50})
	cellGroup.append({"name":"Control5","startIdx":45,"endIdx":47})
	cellGroup.append({"name":"Control6","startIdx":42,"endIdx":44})
	cellGroup.append({"name":"Control7","startIdx":39,"endIdx":41})
	cellGroup.append({"name":"Control8","startIdx":36,"endIdx":38})
	cellGroup.append({"name":"Control9","startIdx":33,"endIdx":35})
	cellGroup.append({"name":"Control10","startIdx":30,"endIdx":32})
	return cellGroup

if __name__ == "__main__":
	print getCellGroups()
