/*
    HRLAnalysis(TM) Software License - Version 1.0 - August 27th, 2013

    Permission is hereby granted, free of charge, to any person or 
    organization obtaining a copy of the software and accompanying 
    documentation covered by this license (the "Software") to use, 
    reproduce, display, distribute, execute, and transmit the 
    Software, and to prepare derivative works of the Software, and 
    to permit third-parties to whom the Software is furnished to do 
    so, all subject to the following:

    The copyright notices in the Software and this entire statement, 
    including the above license grant, this restriction and the 
    following disclaimer, must be included in all copies of the 
    Software, in whole or in part, and all derivative works of the 
    Software, unless such copies or derivative works are solely in 
    the form of machine-executable object code generated by a source 
    language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND 
    NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR 
    ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR 
    OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
    OTHER DEALINGS IN THE SOFTWARE, INCLUDING BUT NOT LIMITED TO THE 
    COMPATIBILITY OF THIS LICENSE WITH OTHER SOFTWARE LICENSES.
*/
#ifndef ANALYSISDATA_H_
#define ANALYSISDATA_H_

#include <vector>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <string>
#include <sstream>
#include <algorithm>
#include <math.h>

#define     TOLERANCE   0.01

class AnalysisData {
    public:
        AnalysisData();
        ~AnalysisData();
        bool fillRasterData(std::string fileName);
        bool fillSpikeBins(std::string fileName);
        bool fillSpikeRates(std::string fileName);
        bool fillWindowRates(std::string fileName);
        bool fillCOV(std::string fileName);
        bool fillVoltageData(std::string fileName);

        bool compareRasterData(std::vector<std::pair<int,int> > &data);
        bool compareSpikeBins(std::vector<std::pair<int,int> > &data);
        bool compareSpikeRates(std::vector<std::pair<int,double> > &data);
        bool compareWindowRates(std::vector<std::pair<int,double> > &data);

        bool compareSpikeBinsAt(std::vector<int> &data, int loc);

        bool compareRasterData(std::vector<int> &data, int dimension);
        bool compareSpikeBins(std::vector<int> &data, int dimension);
        bool compareSpikeRates(std::vector<int> &data);
        bool compareWindowRates(std::vector<int> &data);
        bool compareSpikeRates(std::vector<double> &data);
        bool compareWindowRates(std::vector<double> &data);
        bool compareCOV(std::vector<double> &data);

        bool compareVoltageData(std::vector< std::vector<float> > &data, float tol);

        //void dumpRaster();
        //void dumpSpikeBins();
        //void dumpSpikeRates();
        //void dumpWindowRates();
    private:
        bool fillData(std::vector<std::pair<int,int> > &data, std::string fileName);
        bool fillData(std::vector<std::pair<int,double> > &data, std::string fileName);
        bool fillData(std::vector< std::vector<float> > &data, std::string fileName);
        bool compareData(std::vector<std::pair<int,int> > &data1, std::vector<std::pair<int,int> > &data2);
        bool compareData(std::vector<std::pair<int,double> > &data1, std::vector<std::pair<int,double> > &data2);

        bool compareData(std::vector<std::pair<int,int> > &data1, std::vector<int> &data2, int dimension);
        bool compareData(std::vector<std::pair<int,double> > &data1, std::vector<double> &data2);
        bool compareData(std::vector<std::pair<int,double> > &data1, std::vector<int> &data2);
        
        bool compareData(std::vector<float> &data1, std::vector<float> &data2, float tol);
        bool compareData(std::vector< std::vector<float> > &data1, std::vector< std::vector<float> > &data2, float tol);

        static void printIntPair(std::pair<int,int> iPair);
        static void printDblPair(std::pair<int,double> iPair);
    private:
        std::vector<std::pair<int,int> > rasterData_;
        std::vector<std::pair<int,int> > spikeBins_;
        std::vector<std::pair<int,double> > spikeRates_;
        std::vector<std::pair<int,double> > windowRates_;
        std::vector<std::pair<int,double> > COV_;
        std::vector< std::vector<float> > voltageData_;
};

#endif /* ANALYSISDATA_H_ */
