/*
    HRLAnalysis(TM) Software License - Version 1.0 - August 27th, 2013

    Permission is hereby granted, free of charge, to any person or 
    organization obtaining a copy of the software and accompanying 
    documentation covered by this license (the "Software") to use, 
    reproduce, display, distribute, execute, and transmit the 
    Software, and to prepare derivative works of the Software, and 
    to permit third-parties to whom the Software is furnished to do 
    so, all subject to the following:

    The copyright notices in the Software and this entire statement, 
    including the above license grant, this restriction and the 
    following disclaimer, must be included in all copies of the 
    Software, in whole or in part, and all derivative works of the 
    Software, unless such copies or derivative works are solely in 
    the form of machine-executable object code generated by a source 
    language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND 
    NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR 
    ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR 
    OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
    OTHER DEALINGS IN THE SOFTWARE, INCLUDING BUT NOT LIMITED TO THE 
    COMPATIBILITY OF THIS LICENSE WITH OTHER SOFTWARE LICENSES.
*/
#ifndef HRLNEURALANALYSISHRLSIM_H
#define HRLNEURALANALYSISHRLSIM_H

#include <HrlNeuralAnalysis.h>
#include <boost/serialization/base_object.hpp>

namespace boost {
namespace serialization {
	class access;
}
}

namespace hrlAnalysis {

class HrlNeuralAnalysisHRLSim : public HrlNeuralAnalysis
{
    public:
		HrlNeuralAnalysisHRLSim();
        /**
         * Base constructor
         *
         * @param startTime the point in time to begin extracting spiking information.
         * @param endTime when to stop extracting information.
         * @param startIdx the starting cell index for neurons to be extracted.
         * @param endIdx the last index of the neurons to be extracted.
         * @param fileNames the bin files containing the simulations results.
         */
        HrlNeuralAnalysisHRLSim(int startTimeIn, int endTimeIn, int startIdxIn, int endIdxIn, std::vector<std::string> fileNames);
        /**
         * Base destructor
         */
        virtual ~HrlNeuralAnalysisHRLSim();
        /**
         * Create the data structures used for analysis.  The spike times and neuron indexes,
         * within the specified ranges, are extracted from the given bin files.
         * @return Success
         */
        virtual bool buildDataStructures();
    private:
        uint processFile(std::ifstream &fpIn);
        void processLine(std::vector<int> &line, uint numSpikes, int time);
        uint offset_;

        friend class boost::serialization::access;
        template <typename Archive>
        void serialize(Archive& ar, const unsigned version) {
        	ar & boost::serialization::base_object<HrlNeuralAnalysis>(*this);
        }

};

typedef boost::shared_ptr<HrlNeuralAnalysisHRLSim> HrlNeuralAnalysisHRLSimPtr;

}

#endif /* HRLNEURALANALYSISHRLSIM_H */
