/*
    HRLAnalysis(TM) Software License - Version 1.0 - August 27th, 2013

    Permission is hereby granted, free of charge, to any person or 
    organization obtaining a copy of the software and accompanying 
    documentation covered by this license (the "Software") to use, 
    reproduce, display, distribute, execute, and transmit the 
    Software, and to prepare derivative works of the Software, and 
    to permit third-parties to whom the Software is furnished to do 
    so, all subject to the following:

    The copyright notices in the Software and this entire statement, 
    including the above license grant, this restriction and the 
    following disclaimer, must be included in all copies of the 
    Software, in whole or in part, and all derivative works of the 
    Software, unless such copies or derivative works are solely in 
    the form of machine-executable object code generated by a source 
    language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
    OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND 
    NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR 
    ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR 
    OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING 
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
    OTHER DEALINGS IN THE SOFTWARE, INCLUDING BUT NOT LIMITED TO THE 
    COMPATIBILITY OF THIS LICENSE WITH OTHER SOFTWARE LICENSES.
*/
#include <HrlNeuralAnalysisHRLSim.h>

using namespace hrlAnalysis;
using namespace std;

HrlNeuralAnalysisHRLSim::HrlNeuralAnalysisHRLSim():HrlNeuralAnalysis() {}

HrlNeuralAnalysisHRLSim::HrlNeuralAnalysisHRLSim(int startTimeIn, int endTimeIn, int startIdxIn,
                                                 int endIdxIn, std::vector<std::string> fileNames):
                                                 HrlNeuralAnalysis(startTimeIn,endTimeIn,startIdxIn,endIdxIn,fileNames) {}

HrlNeuralAnalysisHRLSim::~HrlNeuralAnalysisHRLSim() {}

bool HrlNeuralAnalysisHRLSim::buildDataStructures() {

    bool retVal(true);
    uint procReturn(0);
    ifstream fpIn;
    offset_ = 0;

    assert(sizeof(int) == 4);
    assert(sizeof(uint) == 4);

    // Clear out the existing data structures if needed.
    clearDataStructures();
    // allocate the cell spike array.
    cellActivity_->resize(paramsIn_->endIdx - paramsIn_->startIdx + 1);
    // Loop through the input files and process the spike data.
    BOOST_FOREACH( string file, paramsIn_->fileNames ) {
        // Open the binary file
        fpIn.open(file.c_str(),ios::in);
        if(!fpIn.fail()) {
            procReturn = processFile(fpIn);
            offset_ += procReturn;
        } else {
            cerr << "Failed to correctly open file: \n\t" << file << endl;
            retVal = false;
        }
        fpIn.close();

        if(-1 == procReturn)
            break;

    }

    paramsIn_->isDataCompiled = true;

    return retVal;
}

uint HrlNeuralAnalysisHRLSim::processFile(ifstream &fpIn) {
    uint size(0);
    uint numSpikes(0);
    vector<int> line;
    // Read in the size number of lines in the file.
    fpIn.read((char*) &size, sizeof(uint));
    // Loop through and process the file.
    for(uint i=0; i<size; i++) {
        fpIn.read((char *) &numSpikes, sizeof(uint));
        // Check if we need to resize the line vector.
        if(line.size() < numSpikes) {
            line.resize(numSpikes+1);
        }
        // Load the line vector.
        fpIn.read((char*) &line[0], sizeof(int) * numSpikes);

        if(!fpIn.good()) {
            cerr << "Error reading from file." << endl;
            return 0;
        } else if( (i+offset_) <= paramsIn_->endTime && (i+offset_) >= paramsIn_->startTime) {
            processLine(line, numSpikes, (i+offset_));
        } else if((i+offset_) > paramsIn_->endTime){
            size = -1;
            break;
        }
    }
    return size;
}

void HrlNeuralAnalysisHRLSim::processLine(vector<int> &line, uint numSpikes, int time) {
    // process the line.  Are we within the time range?
    for(uint j = 0; j<numSpikes; j++) {
        if(line.at(j) <= paramsIn_->endIdx && line.at(j) >= paramsIn_->startIdx  ) {
            // Add the pair to the spike time array.
            spikeActivity_->push_back( make_pair(time,line.at(j)));
            // Add the time to the cell spike information.
            cellActivity_->at(line.at(j) - paramsIn_->startIdx).push_back(time);
        }
    }
}

