#
# This file was automatically generated by the hrlAnalysis Software.
#

def getCellGroups():
	cellGroup = []
	cellGroup.append({"name":"Marker","startIdx":0,"endIdx":0})
	cellGroup.append({"name":"TC","startIdx":1,"endIdx":2})
	cellGroup.append({"name":"GPE","startIdx":3,"endIdx":18})
	cellGroup.append({"name":"GPI","startIdx":19,"endIdx":34})
	cellGroup.append({"name":"STN","startIdx":35,"endIdx":50})
	return cellGroup

if __name__ == "__main__":
	print getCellGroups()
